# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-10 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAttributes',
            fields=[
                ('BA_id', models.AutoField(primary_key=True, serialize=False)),
                ('BA_time', models.DateTimeField(auto_now=True)),
                ('BA_change_time', models.DateTimeField(auto_now_add=True)),
                ('BA_state', models.IntegerField(verbose_name=2)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=10)),
                ('price_m', models.FloatField(max_length=10)),
                ('choices', models.CharField(choices=[(1, '0室0厅0厨0卫'), (2, '1室1厅1厨1卫'), (3, '2室1厅1厨1卫'), (4, '2室2厅1厨1卫'), (5, '3室2厅1厨1卫'), (6, '3室2厅1厨2卫'), (7, '3室1厅1厨1卫'), (8, '2室0厅1厨1卫'), (9, '1室0厅1厨1卫'), (10, '1室2厅1厨1卫'), (11, '4室2厅1厨2卫'), (12, '4室1厅1厨4卫'), (13, '2室2厅1厨2卫'), (14, '5室2厅1厨2卫'), (15, '2室1厅1厨2卫'), (16, '3室1厅1厨2卫'), (17, '3室0厅1厨1卫'), (18, '5室3厅1厨2卫'), (19, '4室1厅1厨1卫'), (20, '4室2厅2厨2卫'), (21, '3室2厅1厨3卫'), (22, '5室1厅1厨1卫'), (23, '1室0厅0厨1卫'), (24, '6室4厅2厨3卫'), (25, '4室2厅1厨5卫'), (26, '5室2厅1厨3卫')], max_length=8)),
                ('floor', models.CharField(max_length=20)),
                ('structure', models.CharField(choices=[(1, '平层'), (2, '复式'), (3, '错层'), (4, '跃层'), (5, '暂无数据')], max_length=5)),
                ('orientation', models.CharField(max_length=10)),
                ('decoration', models.CharField(max_length=2)),
                ('agent_name', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': '房屋基本信息',
                'db_table': 'tb_house_basic',
            },
        ),
    ]
