# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-13 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20210413_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicattributes',
            name='choices',
            field=models.IntegerField(choices=[(1, '0室0厅0厨0卫'), (2, '1室1厅1厨1卫'), (3, '2室1厅1厨1卫'), (4, '2室2厅1厨1卫'), (5, '3室2厅1厨1卫'), (6, '3室2厅1厨2卫'), (7, '3室1厅1厨1卫'), (8, '2室0厅1厨1卫'), (9, '1室0厅1厨1卫'), (10, '1室2厅1厨1卫'), (11, '4室2厅1厨2卫'), (12, '4室1厅1厨4卫'), (13, '2室2厅1厨2卫'), (14, '5室2厅1厨2卫'), (15, '2室1厅1厨2卫'), (16, '3室1厅1厨2卫'), (17, '3室0厅1厨1卫'), (18, '5室3厅1厨2卫'), (19, '4室1厅1厨1卫'), (20, '4室2厅2厨2卫'), (21, '3室2厅1厨3卫'), (22, '5室1厅1厨1卫'), (23, '1室0厅0厨1卫'), (24, '6室4厅2厨3卫'), (25, '4室2厅1厨5卫'), (26, '5室2厅1厨3卫')], max_length=1, verbose_name='户型'),
        ),
        migrations.AlterField(
            model_name='basicattributes',
            name='floor',
            field=models.IntegerField(max_length=1, verbose_name='楼层'),
        ),
    ]
