# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-13 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20210413_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedproperties',
            name='DP_id',
        ),
        migrations.DeleteModel(
            name='DetailedProperties',
        ),
    ]
