# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20210413_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicattributes',
            name='BA_change_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='basicattributes',
            name='BA_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
