# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_basicattributes_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicattributes',
            name='decoration',
            field=models.IntegerField(choices=[(1, '毛坯'), (2, '简装'), (3, '精装'), (4, '其他')], verbose_name='装修情况'),
        ),
    ]
