# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-15 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_auto_20210413_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicattributes',
            name='region',
            field=models.CharField(default='', max_length=10, verbose_name='地区'),
        ),
    ]
