# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-24 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_basicattributes_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False, verbose_name='标准ID')),
                ('house_state', models.IntegerField(choices=[(0, '停止交易'), (1, '入库'), (2, '可以交易')], verbose_name='房源状态')),
                ('name', models.CharField(max_length=200, verbose_name='房源描述')),
                ('price', models.FloatField(max_length=10, verbose_name='房源价格')),
                ('price_m', models.FloatField(max_length=10, verbose_name='每平米价格')),
                ('choices', models.CharField(max_length=10, verbose_name='户型')),
                ('floor', models.CharField(max_length=20, verbose_name='楼层')),
                ('area', models.CharField(default='', max_length=10, verbose_name='房源面积')),
                ('structure', models.CharField(max_length=10, verbose_name='户型结构')),
                ('inside_area', models.CharField(max_length=15, verbose_name='套内面积')),
                ('building_type', models.CharField(max_length=15, verbose_name='建筑类型')),
                ('orientation', models.CharField(max_length=10, verbose_name='房屋朝向')),
                ('building_structure', models.CharField(max_length=10, verbose_name='建筑结构')),
                ('decoration', models.CharField(max_length=10, verbose_name='装修情况')),
                ('proportion', models.CharField(max_length=15, verbose_name='梯户比例')),
                ('lift', models.CharField(max_length=10, verbose_name='是否配备电梯')),
                ('listing_time', models.DateTimeField(verbose_name='挂牌时间')),
                ('transaction_type', models.CharField(max_length=15, verbose_name='交易权属')),
                ('last_time', models.DateTimeField(verbose_name='上次交易')),
                ('purpose', models.CharField(max_length=4, verbose_name='房屋用途')),
                ('ascription_year', models.CharField(max_length=4, verbose_name='房屋年限')),
                ('property_right', models.CharField(max_length=10, verbose_name='产权所属')),
                ('mortgage', models.CharField(max_length=20, verbose_name='抵押信息')),
                ('premises_permit', models.CharField(max_length=10, verbose_name='房本备件')),
                ('image_add', models.CharField(max_length=200, verbose_name='图片存储地址')),
                ('agent_name', models.CharField(max_length=5, verbose_name='经纪人')),
                ('region', models.CharField(default='', max_length=10, verbose_name='地区')),
            ],
            options={
                'verbose_name': '房屋信息',
                'verbose_name_plural': '房屋信息',
                'db_table': 'house_info',
            },
        ),
    ]
