# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-24 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0016_houseinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedproperties',
            name='DP_id',
        ),
        migrations.RemoveField(
            model_name='transactionattribute',
            name='TA_id',
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='listing_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='挂牌时间'),
        ),
        migrations.DeleteModel(
            name='BasicAttributes',
        ),
        migrations.DeleteModel(
            name='DetailedProperties',
        ),
        migrations.DeleteModel(
            name='TransactionAttribute',
        ),
    ]
