# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-24 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0017_auto_20210424_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseinfo',
            name='last_time',
        ),
    ]
