# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-05-02 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0018_remove_houseinfo_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='listing_time',
            field=models.DateField(auto_now_add=True, verbose_name='挂牌时间'),
        ),
    ]
